name: 'Custom Curl Request'
description: 'A custom GitHub Actions for making a curl request'
author: 'Your Name'
inputs:
  url:
    description: 'The URL to make the curl request to'
    required: true
  method:
    description: 'The HTTP method to use for the request'
    required: false
    default: 'GET'
runs:
  using: 'composite'
  steps:
    - run: |
        curl -X ${{ inputs.method }} ${{ inputs.url }}