name: 10-output-test
on:
  
  repository_dispatch: 
    types: [test]

  workflow_dispatch:
    inputs:
      msg:
        description: 'msg'
        required: false
        default: 'hello'
         
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo type
        run: echo ${{ github.event_name }}
      - name: setOutputs
        id: step1
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "::set-output name=msg::${{ github.event.client_payload.msg || github.event.inputs.msg || 'default' }}"
          else
            echo "::set-output name=msg::${{ github.event.inputs.msg }}"
          fi
        shell: bash
      - name: echo
        run: echo ${{ steps.step1.outputs.msg }}
  