name: Git Clone and Version

on: [push]

jobs:
  git-clone-and-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: hexf00/actions-test  # 将 owner/repo 替换为您要克隆的仓库的所有者和名称

    - name: Show Git version
      run: git --version