name: Mixed inputs
# https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/

# Using environment in github actions without creating Deployments #36919
# https://github.com/orgs/community/discussions/36919

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:

    - name: show inputs
      run: echo '${{ toJSON(github.event.inputs) }}' | jq .

    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"

    - name: echo environment
      run: echo ${{ github.event.inputs.environment }}

    - name: echo vars
      run: echo ${{ vars.TEST }}

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:

    - name: show inputs
      run: echo '${{ toJSON(github.event.inputs) }}' | jq .

    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"

    - name: echo environment
      run: echo ${{ github.event.inputs.environment }}

    - name: echo vars
      run: echo ${{ vars.TEST }}

    