name: mock build

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: build-${{ github.sha }}
  # cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: echo ref
        run: echo ${{ github.ref }}
      - name: echo sha
        run: echo ${{ github.sha }}

      - name: tmp
        run: echo "tmp" > tmp.txt
      - name: check last build
        id: check_last_build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}-build.txt
          path: build.txt
        continue-on-error: true
      
      # 如果有对应的artifact，就跳过build

        
      - name: mock build
        run: sleep 3 && echo "${{ github.sha }}" > build.txt
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}-build.txt
          path: build.txt