name: mock deploy2

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/mock-build.yml
  build-image:
    uses: ./.github/workflows/mock-build-image.yml
    needs: build
  deploy:
    runs-on: ubuntu-latest
    needs: [build-image]
    steps:
      - name: get build-image artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.ref }}-build-image.txt
          path: build-image.txt
      
      - name: mock deploy2
        run: echo build-image.txt