name: mock deploy1

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/mock-build.yml
  build-image:
    uses: ./.github/workflows/mock-build-image.yml
    needs: build
  deploy:
    runs-on: ubuntu-latest
    needs: [build-image]
    steps:
      - name: get build-image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.sha }}-build-image.txt
          path: build-image.txt
      
      - name: mock deploy1
        run: echo build-image.txt